acanalesprueba_homepage:
    path:     /hola/{name}
    defaults: { _controller: acanalespruebaBundle:Default:index }
acanalesprueba_list:
    path:     /hola2/{name}
    defaults: { _controller: acanalespruebaBundle:Default:list }
acanalesprueba_calular:
    path:     /calcular
    defaults: { _controller: acanalespruebaBundle:Default:calcular }
