acanales_user:
    resource: "@acanalesUserBundle/Resources/config/routing.yml"
    prefix:   /

acanalesequipo:
    resource: "@acanalesequipoBundle/Resources/config/routing.yml"
    prefix:   /

acanales_recetas:
    resource: "@acanalesRecetasBundle/Resources/config/routing.yml"
    prefix:   /

acanalesprueba:
    resource: "@acanalespruebaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login_route:
    path:     /login
    defaults: { _controller: acanalesequipoBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout	