acanalesequipo_equipo:
    path:     /{_locale}/equipo/{nombre}
    defaults: { _controller: acanalesequipoBundle:Default:equipo }		
acanalesequipo_clasificacion:
    path:     /{_locale}/clasificacion
    defaults: { _controller: acanalesequipoBundle:Default:clasificacion }	
acanalesequipo_crearequipo:
    path:     /crear-equipo
    defaults: { _controller: acanalesequipoBundle:Default:crearEquipo }	
acanalesequipo_gestionEquipos:
    path:     /gestion-equipos
    defaults: { _controller: acanalesequipoBundle:Default:gestionEquipos }
acanalesequipo_editarEquipo:
    path:     /editar-equipo/{id}
    defaults: { _controller: acanalesequipoBundle:Default:editarEquipo }			

