acanalesequipo_homepage:
    path:     /{_locale}/equipo/{nombre}
    defaults: { _controller: acanalesequipoBundle:Default:index, _locale:en }
acanalesequipo_equipocreado:
    path:     /{_locale}/equipo-creado
    defaults: { _controller: acanalesequipoBundle:Default:equipoCreado, _locale: en }	
    requirements:
       _locale: en|es
acanalesequipo_crearequipo:
    path:     /crear-equipo
    defaults: { _controller: acanalesequipoBundle:Default:crearEquipo }	
acanalesequipo_equipos:
    path:     /equipos
    defaults: { _controller: acanalesequipoBundle:Default:equipos }	
acanalesequipo_bootstrap:
    path:     /bootstrap
    defaults: { _controller: acanalesequipoBundle:Default:bootstrap }	

