services:
#    acanalesequipo.example:
#        class: acanales\equipoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    equipos.clasificacion:
        class: acanales\equipoBundle\Model\Clasificacion
        arguments: [@doctrine.orm.entity_manager]