<?php

namespace acanales\equipoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquiposRepository extends EntityRepository
{
}
