acanales_user_homepage:
    path:     /{_locale}/hello/{name}
    defaults: { _controller: acanalesUserBundle:Default:index }
acanales_user_crearUsuario:
    path:     /{_locale}/registro
    defaults: { _controller: acanalesUserBundle:Default:crearUsuario }
acanales_user_editarUsuario:
    path:     /editar-usuario/{id}
    defaults: { _controller: acanalesUserBundle:Default:editarUsuario }	
acanales_user_gestionUsuarios:
    path:     /gestion-usuarios
    defaults: { _controller: acanalesUserBundle:Default:gestionUsuarios }	
acanales_user_eliminarUsuario:
    path:     /eliminar-usuario/{id}
    defaults: { _controller: acanalesUserBundle:Default:eliminarUsuario }		
acanales_user_areaPrivada:
       path:   /area-privada
       defaults: { _controller: acanalesUserBundle:Default:areaPrivada }
acanales_user_logout:
       pattern:   /logout
acanales_contacto:
    path:     /{_locale}/contacto
    defaults: { _controller: acanalesUserBundle:Default:contacto }