acanales_recetas_homepage:
    path:     /recipes/{id}
    defaults: { _controller: acanalesRecetasBundle:Default:index }
acanales_recetas_list:
    path:     /receta/{nombre}
    defaults: { _controller: acanalesRecetasBundle:Default:list }
